[project]
name = "mall-customers-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "pytest>=8.4.2",
    "ruff>=0.12.12",
    "scikit-learn>=1.7.1",
]
